apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nodeserver"
  labels:
    app: "nodeserver"
spec:
  selector:
    matchLabels: 
      app: nodeserver
  replicas: 1
  template:
    metadata:
      name: "nodeserver"
      labels:
        app: "nodeserver"
    spec:
      containers:
        - name: nodeserver
          image: "ilgssonbraga/hello-nodejs-kind:v6.1"
          envFrom:
            - configMapRef: 
                name: nodeserver-env
          volumeMounts:
            - mountPath: "/app/myfamily"
              name:  config
      volumes:
        - name: config
          configMap: 
            name: configmap-family
            items:
            - key: members
              path: "myfamily.txt"
