apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nodeserver"
  labels:
    app: "nodeserver"
spec:
  selector:
    matchLabels: 
      app: nodeserver
  replicas: 1
  template:
    metadata:
      name: "nodeserver"
      labels:
        app: "nodeserver"
    spec:
      containers:
        - name: nodeserver
          image: "ilgssonbraga/hello-nodejs-kind:7.5"

          resources:
            requests:
              cpu: "0.5"
              memory: 20Mi
            limits:
              cpu: "0.5"
              memory: 25Mi

          # startupProbe:
          #   httpGet: 
          #     path: /healthz
          #     port: 3333
          #   failureThreshold: 20
          #   periodSeconds: 3
          #   timeoutSeconds: 1

          # readinessProbe:
          #   httpGet: 
          #     path: /healthz
          #     port: 3333
          #   failureThreshold: 1
          #   periodSeconds: 3
          #   timeoutSeconds: 1
          # livenessProbe:
          #   httpGet: 
          #     path: /healthz
          #     port: 3333
          #   periodSeconds: 3
          #   failureThreshold: 1
          #   timeoutSeconds: 1
          #   successThreshold: 1
          envFrom:
            - configMapRef: 
                name: nodeserver-env
            - secretRef: 
                name: nodeserver-secret
          volumeMounts:
            - mountPath: "/app/myfamily"
              name:  config
      volumes:
        - name: config
          configMap: 
            name: configmap-family
            items:
            - key: members
              path: "myfamily.txt"
