apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nodeserver"
  labels:
    app: "nodeserver"
spec:
  selector:
    matchLabels: 
      app: nodeserver
  replicas: 1
  template:
    metadata:
      name: "nodeserver"
      labels:
        app: "nodeserver"
    spec:
      containers:
        - name: nodeserver
          image: "ilgssonbraga/hello-nodejs-kind:v5"
          envFrom:
            - configMapRef: 
                name: nodeserver-env
