apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejsserver-pvc
spec:
  # capacity: 
  #   storage: 50Gi
  accessModes:
    - ReadWriteOnce
    # - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
      